# -*- coding: utf-8 -*-
"""Priyadharshini Devi_assignment3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TukNYyMs5-9z_COFSOzSSbz1koMdQCEu

# Exercises
Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

What is 7 to the power of 4?
"""

print(7**4)

"""Split this string:

s = "Hi there Sam!"

into a list.
"""

s="Hi there sam!"
s=s.split()
print(s)

"""Given the variables:

planet = "Earth"
diameter = 12742

Use .format() to print the following string:

The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

print("The diameter of {} is {} kilometers.".format('Earth',12742))

"""Given this nested list, use indexing to grab the word "hello"
"""

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

lst[3][1][2][0]

"""Given this nest dictionary grab the word "hello". Be prepared, this will be annoying/tricky"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d['k1'][3]['tricky'][3]['target'][3]

"""What is the main difference between a tuple and a list?

The list is dynamic, whereas the tuple has static characteristics. This means that lists can be modified whereas tuples cannot be modified, the tuple is faster than the list because of static in nature. Lists are denoted by the square brackets but tuples are denoted as parenthesis.

Create a function that grabs the email website domain from a string in the form:

user@domain.com

So for example, passing "user@domain.com" would return: domain.com
"""

def domainGet(email):
    print("Your domain is: " + email.split('@')[-1])

email = input("Please enter your email: >")

domainGet(email)

"""Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization."""

def word(get):
    if get == "dog":
        print("True")
    else:
        print("False")
get = input()

word(get)

"""Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases."""

string = input("Please enter your string: ")

def countdogs(string):
    count = 0
    for word in string.lower().split():
        if word == 'dog' or word == 'dogs':
            count = count + 1
            print(count)

countdogs(string)

"""# Problem
You are driving a little too fast, and a police officer stops you. Write a function to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". If your speed is 60 or less, the result is "No Ticket". If speed is between 61 and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all cases
"""

def caught_speeding(speed, is_birthday):
    
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'

print("Please enter the speed(km/h)(only number please): \n")
speed = int(input("> "))

print("Please enter your birthday: (in DD/MM/YYYY format)\n")
birthday = str(input("> "))

def speeding(speed, birthday):
    if birthday == '29/08/1989':
        s = speed - 5
    else:
        s = speed

    if s <= 60:
        print("You pass.")
    elif s > 61 and s <= 80:
        print("You get a small ticket")
    else:
        print("You get a big ticket.")

speeding(speed, birthday)

print("Please enter the speed(km/h)(only number please): \n")
speed = int(input("> "))

print("Please enter your birthday: (in DD/MM/YYYY format)\n")
birthday = str(input("> "))

def speeding(speed, birthday):
    if birthday == '29/08/1989':
        s = speed - 5
    else:
        s = speed

    if s <= 60:
        print("You pass.")
    elif s > 61 and s <= 80:
        print("You get a small ticket")
    else:
        print("You get a big ticket.")

speeding(speed, birthday)

"""Create an employee list with basic salary values(at least 5 values for 5 employees) and using a for loop retreive each employee salary and calculate total salary expenditure."""

employeeName=["raj","ram","sam","santhosh","vijay"]
print(employeeName)
salary=[230000,220000,250000,240000,200000]
print(salary)
add=0
for i in salary:
   add=add+i
print("total:-",add)

"""Create two dictionaries in Python:

First one to contain fields as Empid, Empname, Basicpay

Second dictionary to contain fields as DeptName, DeptId.

Combine both dictionaries
"""

def merge(d1,d2):
    res = {**d1, **d2}
    return res
d1 = {'Empid':123, 'Empname':"arjun" , 'Basicpay':2000}
d2 = {'deptName':"cse" , 'Deptid':2120}
print(merge(d1,d2))